### ISSUE TITLE
Can't Find Module 'request'

### ISSUE THREAD

**Issue by Aaronm14** [JustMaier/node-cratejoy#1]
I'm pretty sure there's a decent chance this is just due to my lack of Node experience, but I created a folder, than ran "npm install node-cratejoy"  Afterwards I just created test.js with the below code.  I just needed to run "npm install request" and my code was able to run.  I don't know if this is something people just need to do, or if it should be added as a dependency in your package.json?

test.js:

```
var cratejoyAPI = require('node-cratejoy');
var cratejoy = new cratejoyAPI (
        '[clientid]',
        '[clientsecret]'
);

cratejoy.getSubscriptions(function(err, res, body) {
        if(err) throw err;
        console.log('Got it!');
        console.log(body);
});
```

error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new module.exports (/Users/aaronm14/node_projects/cratejoy/node_modules/node-cratejoy/nodecratejoy.js:2:16)
    at Object.<anonymous> (/Users/aaronm14/node_projects/cratejoy/test.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by JustMaier** [comment]
Hey @Aaronm14,
You're right I didn't include `request` as a dependency because I assumed that usually someone using this would already have `request` and I didn't want to require a different version. I've seen it in a few other packages like this so I assumed it was a best practice for small API wrappers like this. I'm going to go ahead and add a note about it to the README

**Comment by Aaronm14** [comment]
@JustMaier - Good to know.  Works for me.

Quick question unrelated to this - any idea why my code in test.js didn't return anything (I have my client id/secret from my Cratejoy admin)?  It says undefined in my console when it logs the body

**Comment by JustMaier** [comment]
It's possible that you don't actually have a real client id/secret yet. As far as I know CrateJoy hasn't actually publicly released their API. The client id/secret was actually given to me by someone on the dev team for testing. I know that it also has it in the control panel, but I don't think those are actually active yet...

You can try using something like [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en) or CURL to see if you can actually get a response from the API without this module.
