### ISSUE TITLE
How can I make your plugin work in browser?

### ISSUE THREAD

**Issue by montrealblau** [JustMaier/node-cratejoy#2]
Thanks!

**Comment by JustMaier** [comment]
Hey @montrealblau, unfortunately this plugin cannot work in a browser.

**Comment by montrealblau** [comment]
I edited request headers and installed chrome extension - CORS.
it's hacky but works. I did that because its the only way I know, lol

@JustMaier can you please describe your workflow with this module? i'm just starting out with node... would love to learn more about it and understand how to use it. thanks

**Comment by JustMaier** [comment]
Hey @montrealblau, here's a [quick sample](https://gist.github.com/JustMaier/08345aebc33a0b6b273fec72ee55f2a5)

**Comment by montrealblau** [comment]
@JustMaier thank you so much! Its awesome, now it all makes sense!! appreciate

**Comment by JustMaier** [comment]
Glad I could help :)
