### ISSUE TITLE
problems with UTF-8

### ISSUE THREAD

**Issue by montrealblau** [JustMaier/node-cratejoy#3]
doesn't work with utf-8 characters. Any ideas how to fix this? 

Thanks!

**Comment by JustMaier** [comment]
What part of this is giving you trouble with UTF-8?

**Comment by montrealblau** [comment]
when I update product names in my native language, the cratejoy server responds error
{ errors: [ { name: 'Unknown error' } ] }
works fine with english characters, there is some encoding issue with Latvian characters that i dont know how to fix.

**Comment by JustMaier** [comment]
Does it give you the same error when you try to post to the API directly
with a tool like Postman or Fiddler?

**Comment by montrealblau** [comment]
i tried, it doesn't work.

maybe you can play with Postman? ill give you authentication credentials,
jus try to change name of product. It doesnt work if i want to update
product name with special characters that exists in my language.

it added 2 examples
one, that works and other that doesn't/

[image: Inline images 1][image: Inline images 2]

**Comment by JustMaier** [comment]
Hey @montrealblau, You'll wanna connect with the [cratejoy team](mailto:support@cratejoy.com) to get this one resolved. It sounds like their backend isn't accepting your characters.

**Comment by montrealblau** [comment]
Thanks, man! Your the best!
